# Usa una imagen de Java 17
FROM eclipse-temurin:21-jdk

# Crea un directorio para la aplicación
WORKDIR /app

# Copia el archivo JAR generado por Maven/Gradle al contenedor
COPY target/*.jar app.jar

# Expone el puerto en el que corre la API (cámbialo si usas otro)
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]
