version: "3.9"
services:

  spring-api-image:
    image: coleccion
    container_name: coleccion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: localhost
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: manga_app_pruebas
      MYSQL_USER: sperezp
      MYSQL_PASSWORD: 150919
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: